# Generated by Django 3.1.6 on 2021-02-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='oreder',
            new_name='order',
        ),
    ]
